name: C++ Tests and Documentation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++ doxygen graphviz

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake ..

      - name: Build Project
        working-directory: build
        run: make

      - name: Run Tests
        working-directory: build
        run: ./test

      - name: Generate Doxygen Documentation
        working-directory: build
        run: |
          echo "PROJECT_NAME = My C++ Project" > Doxyfile
          echo "INPUT = ../add.cpp ../subtract.cpp ../test.cpp ../main.cpp" >> Doxyfile
          echo "OUTPUT_DIRECTORY = docs" >> Doxyfile
          doxygen Doxyfile
